const STORE_ID = "USERS";

const TYPES = {
  CLEAN_INVALID_ITEM: "CLEAN_INVALID_ITEM",
  INVALID_ITEM: "INVALID_ITEM",
  ITEM: "ITEM",
  ITEMS: "ITEMS",
  CLEAN_REGISTER: "CLEAN_REGISTER",
  COPY: "COPY",
  SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
};

export { STORE_ID, TYPES };
