export const data = [
  {
    number: "123",
    citizen: "Fulano",
    type: "Descarte irregular de resíduos",
    date: "01/04/2021",
    dateEnd: "02/04/2021",
    neighborhood: "Aeroporto 1",
    status: "Registro do número de ocorrência",
    images: ["foto 1", "foto 2", "foto 3", "foto 4"],
  },
  {
    number: "1234",
    citizen: "Ciclano",
    type: "Desmatamento",
    date: "26/09/2021",
    dateEnd: "28/09/2021",
    neighborhood: "Paulistano",
    status: "Encaminhamento do AI a 2ª Promotoria de Justiça",
    images: ["foto 1", "foto 2", "foto 3", "foto 4"],
  },
  {
    number: "12345",
    citizen: "Beltrano",
    type: "Loteamento irregular",
    date: "29/10/2021",
    dateEnd: "30/10/2021",
    neighborhood: "Jardim Consolação",
    status: "Não procede",
    images: ["foto 1", "foto 2", "foto 3", "foto 4"],
  },
  {
    number: "321",
    citizen: "Ciclano da Silva",
    type: "Maus tratos contra animais",
    date: "12/11/2021",
    dateEnd: "16/11/2021",
    neighborhood: "Piratininga",
    status: "Encaminhamento do AI a Polícia Mílitar Ambiental",
    images: ["foto 1", "foto 2", "foto 3", "foto 4"],
  },
  {
    number: "12543",
    citizen: "Aeltrano Alves",
    type: "Maus tratos contra animais",
    date: "15/04/2021",
    dateEnd: "15/04/2021",
    neighborhood: "São Joaquim",
    status: "Solitação de novas informações",
    images: ["foto 1", "foto 2", "foto 3", "foto 4"],
  },
  {
    number: "34543",
    citizen: "Fulano Dias",
    type: "Desmatamento",
    date: "27/08/2021",
    dateEnd: "29/09/2021",
    neighborhood: "Parque João Leite",
    status: "Encaminhamento do AI a Polícia Mílitar Ambiental",
    images: ["foto 1", "foto 2", "foto 3", "foto 4"],
  },
];
