const STORE_ID = "LOGIN";

const TYPES = {
    CLEAN_INVALID_LOGIN: "CLEAN_INVALID_LOGIN",
    INVALID_LOGIN: "INVALID_LOGIN",
    LOGIN: "LOGIN",
    CLEAN_ALL: "CLEAN_ALL"
}

export { STORE_ID, TYPES } 